server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: api

  data:
    # Configuração do Banco Histórico (MongoDB)
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      database: ${MONGO_DATABASE:url_shortener}

    # Configuração do Banco de Alta Performance (Redis)
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
